Memory Optimization for Surfaces with CPU Read Access
projectceladon/minigbm pull request #150
Opened 2024-08-30 05:35 UTC by nanazhan

Tracked-On: OAM-124103

2024-09-02 03:04 UTC, Shao-Feng requested changes
After revert this patch, Y-tile buffer can not be mapped into linear any more

2024-09-04 05:55 UTC, feijiang1 approved these changes
LGTM

2024-09-04 06:10 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-09-04 16:22 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-09-05 14:32 UTC, feijiang1 commented
> After revert this patch, Y-tile buffer can not be mapped into linear any more

please indicate which scenario will allocate Y-tile buffer and CPU need access this buffer without READ_FLAG passed during buffer allocation.

2024-09-06 04:16 UTC, closed without merging